name: Generate PDF KO

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deployment?"
        default: "WhaTap"

permissions:
  contents: write

env:
  PRINCE_VER: 15.3

jobs:
  build-n-deploy:
    name: Generate PDF
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Install Prince
      run: |
        curl https://www.princexml.com/download/prince-${{ env.PRINCE_VER }}-macos.zip -O
        tar zxf prince-${{ env.PRINCE_VER }}-macos.zip
        cd prince-${{ env.PRINCE_VER }}-macos
        yes "" | sudo ./install.sh

    - name: Install pdfcpu
      run: brew install pdfcpu

    - name: Build PDF
      run: |
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-java --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-java-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-java-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-php --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-php-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-php-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-nodejs --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-nodejs-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-nodejs-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-python --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-python-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-python-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-dotnet --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-dotnet-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-dotnet-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-go --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-apm-go-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-apm-go-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-server --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-server-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-server-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-k8s --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-kubernetes-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-kubernetes-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-postgresql --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-postgresql-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-postgresql-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-oracle --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-oracle-v2-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-oracle-v2-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-oracle-pro --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-oracle-pro-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-oracle-pro-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-mysql --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-mysql-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-mysql-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-mssql --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-mssql-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-mssql-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-tibero --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-tibero-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-tibero-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-cubrid --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-cubrid-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-cubrid-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-altibase --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-altibase-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-altibase-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-redis --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-redis-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-redis-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-mongodb --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-db-mongodb-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-db-mongodb-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-log --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-log-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-log-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-url --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-url-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-url-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-manage --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-manage.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-manage.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-reference --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-reference.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-reference.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-extensions --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-extensions.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-extensions.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-awscloudwatch --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-amazon-cloudwatch.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-amazon-cloudwatch.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-awsecs --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-amazon-ecs.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-amazon-ecs.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-azure --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-azure.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-azure.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-ncloud --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-ncloud.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-ncloud.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-oci --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-oracle-cloud.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-oracle-cloud.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-awslog --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-aws-log-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-aws-log-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-browser --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-browser-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-browser-monitoring.pdf
        npx docusaurus-prince-pdf -u https://docs.whatap.io/cover-npm --prince-args="--javascript --page-size='a4' --page-margin='10mm' --style='$PATH_NAME/print.css'" -o ./pdf/whatap-network-performance-monitoring.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/whatap-network-performance-monitoring.pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WHATAP_DOCS_TOKEN }}
      with:
        tag_name: v2.11.0 # 생성할 Release의 태그 이름
        release_name: "v2.11.0(KO)"
        body: "WhaTap Docs v2.11.0 기준으로 생성되 PDF 파일입니다."
        draft: false
        prerelease: false
    
    - name: Upload all PDFs to Release
      run: |
        for pdf_file in ./pdf/*.pdf; do
          echo "Uploading $pdf_file"
          curl -X POST \
            -H "Authorization: token ${{ secrets.WHATAP_DOCS_TOKEN }}" \
            -H "Content-Type: application/pdf" \
            --data-binary @"$pdf_file" \
            "$(echo '${{ steps.create_release.outputs.upload_url }}' | sed 's/{.*}//')?name=$(basename $pdf_file)"
        done

    # - name: Upload to Release
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.WHATAP_DOCS_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: pdf/whatap-url-monitoring.pdf
    #     asset_name: whatap-url-monitoring.pdf
    #     asset_content_type: application/pdf